scripts: build: add config file
 * add config file to enable configuring the mender artifact key

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # Commands
 DATE="$(command -vp date)"
@@ -21,9 +21,21 @@ PRODUCT="Solidsense"
 RELEASE="dev"
 RELEASE_DATE="$("${DATE}" "+%Y%m%d")"
 ITERATION="00"
-MENDER_ARTIFACT="/home/eric/bin/mender-artifact"
-MENDER_PRIVATE_KEY_FILE="/home/eric/work.kingcheese/Solidrun/solidsense/signing-private-keys/private.key"
-MENDER_PUBLIC_KEY_FILE="/home/eric/work.kingcheese/Solidrun/solidsense/signing-private-keys/public.key"
+CONFIG_FILE="meta-cip-sr-common/scripts/build.conf"
+
+# initialize configuration array
+declare -A config
+config=(
+	[devices]="n6gq n6gsdl solidsense"
+	[product]="Solidsense"
+	[release]="dev"
+	[date]="$("${DATE}" "+%Y%m%d")"
+	[iteration]="00"
+	[customer]=""
+	[mender_artifact]=/home/eric/bin/mender-artifact
+	[mender_private_key_file]="/home/eric/work.kingcheese/Solidrun/solidsense/signing-private-keys/private.key"
+	[mender_public_key_file]="/home/eric/work.kingcheese/Solidrun/solidsense/signing-private-keys/public.key"
+)
 
 # Pretty print
 NC="\\e[0m"
@@ -39,14 +51,49 @@ LIGHT_GREEN="\\e[92m"
 usage () {
 	echo "${PROG_NAME}:"
 	echo "    -H|--hardware <hardware type>                 :default is <all>"
-	echo "    -p|--product <product>                        :default is <Solidsense>"
-	echo "    -r|--release <release version>                :default is <dev>"
-	echo "    -d|--date <date>                              :default is <$("${DATE}" "+%Y%m%d")>"
-	echo "    -i|--iteration <iteration>                    :default is <00>"
+	echo "    -p|--product <product>                        :default is <${config[product]}>"
+	echo "    -r|--release <release version>                :default is <${config[release]}>"
+	echo "    -d|--date <date>                              :default is <${config[date]}>"
+	echo "    -i|--iteration <iteration>                    :default is <${config[iteration]}>"
 	echo "    -c|--customer <customer>                      :default is no specific customer"
+	echo "    -C|--config <config>                          :default is <${CONFIG_FILE}>"
 	echo "    -h|--help"
 	echo ""
 	exit 1
+}
+
+read_config_file () {
+	if [ ! -f "${CONFIG_FILE}" ]; then
+		echo "Config file <${CONFIG_FILE}> not found!"
+		exit 1
+	fi
+	while read -r line ; do
+		if echo "${line}" | grep -F = &>/dev/null; then
+			varname=$(echo "${line}" | cut -d '=' -f 1)
+			config[$varname]=$(echo "${line}" | cut -d '=' -f 2-)
+		fi
+	done < "${CONFIG_FILE}"
+}
+
+override_config_file_values () {
+	if [ -n "${DEVICES}" ]; then
+		config[devices]="${DEVICES}"
+	fi
+	if [ -n "${PRODUCT}" ]; then
+		config[product]="${PRODUCT}"
+	fi
+	if [ -n "${RELEASE}" ]; then
+		config[release]="${RELEASE}"
+	fi
+	if [ -n "${DATE}" ]; then
+		config[date]="${DATE}"
+	fi
+	if [ -n "${ITERATION}" ]; then
+		config[iteration]="${ITERATION}"
+	fi
+	if [ -n "${CUSTOMER}" ]; then
+		config[customer]="${CUSTOMER}"
+	fi
 }
 
 find_customer () {
@@ -112,7 +159,8 @@ do_update_manifest () {
 					echo "${pkg} ${rest} <GPL>"
 				;;
 			*-dev )
-				license_pkg="$(echo "$pkg" | sed 's/-dev//')"
+				#license_pkg="$(echo "$pkg" | sed 's/-dev//')"
+				license_pkg="${pkg//-dev//}"
 				if [ -d "${LICENSE_DIR}/${license_pkg}" ] ; then
 					RECIPE_INFO="${LICENSE_DIR}/${license_pkg}/recipeinfo"
 					license="$(awk '/LICENSE/ {gsub("LICENSE: ", ""); print}' < "${RECIPE_INFO}")"
@@ -241,8 +289,8 @@ do_deploy_sign_artifact () {
 		# Sign and verify artifacts
 		printf "    ${RED}%s${NC}" "${device}"
 		START="$(${DATE} +%s)"
-		${MENDER_ARTIFACT} sign --key "${MENDER_PRIVATE_KEY_FILE}" "${mender_artifact}"
-		${MENDER_ARTIFACT} validate --key "${MENDER_PUBLIC_KEY_FILE}" "${mender_artifact}" > /dev/null 2>&1
+		${config[mender_artifact]} sign --key "${config[mender_private_key_file]}" "${mender_artifact}"
+		${config[mender_artifact]} validate --key "${config[mender_public_key_file]}" "${mender_artifact}" > /dev/null 2>&1
 		END="$(${DATE} +%s)"
 		duration="$(calc_duration "${START}" "${END}")"
 		printf " ${YELLOW}(%s)${NC}\\n" "${duration}"
@@ -251,7 +299,7 @@ do_deploy_sign_artifact () {
 
 # main
 
-options=$(getopt -l "help,hardware:,product:,release:,date:,iteration:,customer:" -o "hH:p:r:d:i:c:" -- "${@}")
+options=$(getopt -l "help,hardware:,product:,release:,date:,iteration:,customer:,config:" -o "hH:p:r:d:i:c:C:" -- "${@}")
 eval set -- "${options}"
 
 while true
@@ -265,7 +313,8 @@ do
 			if [ "${1}" = "all" ]; then
 				DEVICES="${HARDWARE_ALL}"
 			else
-				DEVICES=$(echo "${1}" | sed 's/,/ /g')
+				#DEVICES=$(echo "${1}" | sed 's/,/ /g')
+				DEVICES="${1//,/' '}"
 			fi
 			;;
 		-p|--product )
@@ -289,6 +338,9 @@ do
 			CUSTOMER="${1}"
 			CUSTOMER_VER="$(find_customer "${1}")"
 			;;
+		-C|--config )
+			CONFIG_FILE="${1}"
+			;;
 		\? )
 			usage
 			;;
@@ -305,6 +357,12 @@ do
 	esac
 	shift
 done
+
+# Read in the config file
+read_config_file
+
+# Override config file values with option values
+override_config_file_values
 
 if [ "${#}" -ne "0" ]; then
 	usage
